# Generated by Django 5.2.3 on 2025-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
